#!/usr/bin/env python3
"""Extract colorful iconfont symbols and emit overlay-safe SVG sprite + sticker URLs."""

from __future__ import annotations

import json
import re
from pathlib import Path
from urllib.parse import quote

PACKAGE = Path(__file__).resolve().parents[1]
ICONS = PACKAGE / 'src' / 'assets' / 'icons'
OUT_SPRITE = PACKAGE / 'src' / 'client' / 'icon-sprite.ts'
OUT_URLS = PACKAGE / 'src' / 'client' / 'icon-urls.ts'

SYMBOL_RE = re.compile(
    r'<symbol id="icon-([^"]+)" viewBox="([^"]+)">(.*?)</symbol>',
    re.S,
)
SPRITE_RE = re.compile(r"window\._iconfont_svg_string_\d+='(.*)',\(a=>", re.S)

# CSS-hook stickers that official sheets read as `content: url(...)`.
STICKERS = {
    'app': 'tutu',
    'sidebar': 'jumao',
    'composer': 'keainiujiaobao',
    'modal': 'kafei',
    'newSession': 'hudiejie',
    'header': 'xingxing1',
}


def sprite_markup() -> tuple[str, dict[str, tuple[str, str]]]:
    raw = (ICONS / 'iconfont.js').read_text(encoding='utf-8')
    match = SPRITE_RE.search(raw)
    if match is None:
        raise SystemExit('iconfont.js does not contain the SVG sprite string')
    inner = match.group(1)
    symbols: dict[str, tuple[str, str]] = {}
    for name, viewbox, markup in SYMBOL_RE.findall(inner):
        symbols[name] = (viewbox, markup)
    if len(symbols) == 0:
        raise SystemExit('iconfont.js sprite contained no symbols')
    parts = [
        '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"'
        ' aria-hidden="true">',
    ]
    for name, (viewbox, markup) in symbols.items():
        parts.append(f'<symbol id="icon-{name}" viewBox="{viewbox}">{markup}</symbol>')
    parts.append('</svg>')
    return ''.join(parts), symbols


def data_url(viewbox: str, markup: str) -> str:
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{viewbox}">'
        f'{markup}'
        '</svg>'
    )
    return f'url("data:image/svg+xml,{quote(svg, safe="")}")'


def main() -> None:
    sprite, symbols = sprite_markup()
    missing = [name for name in STICKERS.values() if name not in symbols]
    if missing:
        raise SystemExit(f'missing sticker symbols: {missing}')
    urls = {
        key: data_url(*symbols[name])
        for key, name in STICKERS.items()
    }
    OUT_SPRITE.write_text(
        '/** Generated by scripts/embed-icons.py — do not edit by hand. */\n'
        f'export default {json.dumps(sprite)}\n',
        encoding='utf-8',
    )
    url_lines = ',\n'.join(
        f'  {key}: {json.dumps(value)}'
        for key, value in urls.items()
    )
    OUT_URLS.write_text(
        '/** Generated by scripts/embed-icons.py — do not edit by hand. */\n'
        'export const XFZH_STICKER_URL = {\n'
        f'{url_lines},\n'
        '} as const\n',
        encoding='utf-8',
    )
    print(f'symbols {len(symbols)}')
    print(f'icon-sprite.ts {OUT_SPRITE.stat().st_size}')
    print(f'icon-urls.ts {OUT_URLS.stat().st_size}')


if __name__ == '__main__':
    main()
