#!/usr/bin/env python3
"""Subset Jiaotangzi to UI CJK/Latin and emit overlay-safe data-URL @font-face CSS."""

from __future__ import annotations

import base64
import json
from pathlib import Path

from fontTools.subset import Options, Subsetter
from fontTools.ttLib import TTFont

PACKAGE = Path(__file__).resolve().parents[1]
REPO = PACKAGE.parents[2]
FONTS = PACKAGE / 'src' / 'assets' / 'fonts'
OUT_WOFF2 = FONTS / 'jiaotangzi.woff2'
OUT_TS = PACKAGE / 'src' / 'client' / 'webfonts.ts'
SKIP = {'node_modules', 'lib', 'dist', '.git', 'out', '.turbo'}
LOCALE_NAMES = {'locales.ts', 'locale.ts', 'zh.ts', 'en.ts'}


def locale_files() -> list[Path]:
    found: list[Path] = []
    for root_name in ('packages', 'apps'):
        root = REPO / root_name
        if not root.exists():
            continue
        stack = [root]
        while stack:
            current = stack.pop()
            try:
                children = list(current.iterdir())
            except OSError:
                continue
            for child in children:
                if child.name in SKIP:
                    continue
                if child.is_dir():
                    stack.append(child)
                elif child.name in LOCALE_NAMES:
                    found.append(child)
    return found


def charset() -> str:
    chars = {chr(code) for code in range(0x20, 0x7F)}
    chars.update('…—–·•°“”‘’《》【】（）「」『』、，。！？：；￥～　')
    chars.update('xfzh焦糖暖阳猫咖拿铁肉垫')
    for path in locale_files():
        text = path.read_text(encoding='utf-8', errors='ignore')
        for ch in text:
            code = ord(ch)
            if 0x4E00 <= code <= 0x9FFF or 0x3000 <= code <= 0x303F or 0xFF00 <= code <= 0xFFEF:
                chars.add(ch)
    return ''.join(sorted(chars, key=ord))


def subset_jiaotangzi(text: str) -> bytes:
    options = Options()
    options.layout_features = ['*']
    options.desubroutinize = True
    options.flavor = 'woff2'
    font = TTFont(FONTS / 'jiaotangzi.ttf')
    subsetter = Subsetter(options=options)
    subsetter.populate(text=text)
    subsetter.subset(font)
    OUT_WOFF2.parent.mkdir(parents=True, exist_ok=True)
    font.save(OUT_WOFF2)
    return OUT_WOFF2.read_bytes()


def face(family: str, data: bytes, display: str) -> str:
    encoded = base64.b64encode(data).decode('ascii')
    return '\n'.join((
        '@font-face {',
        f"  font-family: '{family}';",
        '  font-style: normal;',
        '  font-weight: 400;',
        f'  font-display: {display};',
        f"  src: url('data:font/woff2;base64,{encoded}') format('woff2');",
        '}',
    ))


def main() -> None:
    text = charset()
    jia = subset_jiaotangzi(text)
    css = '\n\n'.join((
        '/* Generated by scripts/embed-fonts.py — do not edit by hand. */',
        face('Jiaotangzi', jia, 'swap'),
    )) + '\n'
    OUT_TS.write_text(
        '/** Generated by scripts/embed-fonts.py — do not edit by hand. */\n'
        f'export default {json.dumps(css)}\n',
        encoding='utf-8',
    )
    print(f'locale-chars {len(text)}')
    print(f'jiaotangzi.woff2 {OUT_WOFF2.stat().st_size}')
    print(f'webfonts.ts {OUT_TS.stat().st_size}')


if __name__ == '__main__':
    main()
