#!/usr/bin/env python3
"""Crop, compress, and emit overlay-safe WebP data-URL art for the illustrated stage."""

from __future__ import annotations

import io
from pathlib import Path

from PIL import Image

PACKAGE = Path(__file__).resolve().parents[1]
IMAGES = PACKAGE / 'src' / 'assets' / 'images'
OUT_TS = PACKAGE / 'src' / 'client' / 'art.ts'

# role.png is the model sheet only — never embed it.
ASSETS: dict[str, tuple[str, str, int]] = {
    'sceneLight': ('A1.jpg', 'scene', 1920),
    'sceneDark': ('A1-d.jpg', 'scene', 1920),
    'charLeft': ('A3.png', 'character', 1280),
    'charRight': ('B1.png', 'character', 1280),
    'chibi': ('B2.png', 'chrome', 640),
    'lace': ('B3.png', 'chrome', 1024),
    'bowLeft': ('B4-L.png', 'chrome', 480),
    'bowRight': ('B4-R.png', 'chrome', 480),
    'corner': ('B5.png', 'chrome', 420),
    'trimTop': ('B6-trim-1.png', 'chrome', 1600),
    'trimBottom': ('B6-trim-2.png', 'chrome', 1600),
    'crest': ('B6-trim-3.png', 'chrome', 320),
    'settingsFrame': ('B7.png', 'chrome', 900),
    'newSession': ('B8.png', 'chrome', 320),
}

QUALITY = {
    'scene': 70,
    'character': 78,
    'chrome': 80,
}


def crop_alpha(image: Image.Image, pad: int = 6) -> Image.Image:
    if image.mode != 'RGBA':
        return image
    bbox = image.getchannel('A').getbbox()
    if bbox is None:
        return image
    left, top, right, bottom = bbox
    left = max(0, left - pad)
    top = max(0, top - pad)
    right = min(image.width, right + pad)
    bottom = min(image.height, bottom + pad)
    return image.crop((left, top, right, bottom))


def fit(image: Image.Image, kind: str, max_dim: int) -> Image.Image:
    width, height = image.size
    if kind == 'scene':
        scale = min(1.0, max_dim / width)
    elif kind == 'character':
        scale = min(1.0, max_dim / height)
    else:
        scale = min(1.0, max_dim / max(width, height))
    if scale >= 1:
        return image
    size = (max(1, round(width * scale)), max(1, round(height * scale)))
    return image.resize(size, Image.Resampling.LANCZOS)


def encode_webp(image: Image.Image, kind: str) -> bytes:
    payload = image
    if kind == 'scene' and payload.mode not in {'RGB', 'L'}:
        payload = payload.convert('RGB')
    elif kind != 'scene' and payload.mode != 'RGBA':
        payload = payload.convert('RGBA')
    buffer = io.BytesIO()
    payload.save(
        buffer,
        format='WEBP',
        quality=QUALITY[kind],
        method=6,
        lossless=False,
    )
    return buffer.getvalue()


def data_url(data: bytes) -> str:
    from base64 import b64encode
    return 'data:image/webp;base64,' + b64encode(data).decode('ascii')


def main() -> None:
    lines = [
        '/** Generated by scripts/embed-images.py. Do not edit. */',
        '',
        'export const XFZH_ART = {',
    ]
    total = 0
    for name, (filename, kind, max_dim) in ASSETS.items():
        path = IMAGES / filename
        if not path.exists():
            raise SystemExit(f'missing art file: {path}')
        image = Image.open(path)
        image.load()
        image = crop_alpha(image)
        image = fit(image, kind, max_dim)
        encoded = encode_webp(image, kind)
        total += len(encoded)
        url = data_url(encoded)
        print(f'{name:16} {image.size[0]:4}x{image.size[1]:<4}  {len(encoded):7} bytes  {filename}')
        lines.append(f"  {name}: '{url}',")
    lines.append('} as const')
    OUT_TS.write_text('\n'.join(lines) + '\n', encoding='utf-8', newline='\n')
    print(f'wrote {OUT_TS.relative_to(PACKAGE)}  webp={total} bytes  file={OUT_TS.stat().st_size} bytes')


if __name__ == '__main__':
    main()
